/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.CategoriasController;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import modelo.Categorias;
/**
 *
 * @author jaime
 */
public class CategoriasFrame extends JFrame {
    private JTable table;
    private DefaultTableModel model;
    private CategoriasController controller = new CategoriasController();

    public CategoriasFrame() {
        setTitle("Gestión de Categorías");
        setSize(400, 300);
        setLayout(null);

        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"ID", "Nombre"});
        table = new JTable(model);
        JScrollPane scroll = new JScrollPane(table);
        scroll.setBounds(20, 20, 350, 150);
        add(scroll);

        JButton btnCrear = new JButton("Crear");
        btnCrear.setBounds(20, 180, 100, 30);
        add(btnCrear);

        JButton btnEditar = new JButton("Editar");
        btnEditar.setBounds(140, 180, 100, 30);
        add(btnEditar);

        JButton btnEliminar = new JButton("Eliminar");
        btnEliminar.setBounds(260, 180, 100, 30);
        add(btnEliminar);

        JButton btnRefrescar = new JButton("Refrescar");
        btnRefrescar.setBounds(140, 220, 100, 30);
        add(btnRefrescar);

        btnRefrescar.addActionListener(e -> cargarCategorias());

        btnCrear.addActionListener(e -> {
            Categorias c = mostrarDialogo(null);
            if (c != null) controller.crearCategoria(c);
            cargarCategorias();
        });

        btnEditar.addActionListener(e -> {
            int fila = table.getSelectedRow();
            if (fila >= 0) {
                Categorias c = new Categorias();
                c.setId((int) model.getValueAt(fila, 0));
                c.setNombre((String) model.getValueAt(fila, 1));
                c = mostrarDialogo(c);
                if (c != null) controller.actualizarCategoria(c);
                cargarCategorias();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una categoría");
            }
        });

        btnEliminar.addActionListener(e -> {
            int fila = table.getSelectedRow();
            if (fila >= 0) {
                int id = (int) model.getValueAt(fila, 0);
                controller.eliminarCategoria(id);
                cargarCategorias();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una categoría");
            }
        });

        cargarCategorias();
    }

    private void cargarCategorias() {
        model.setRowCount(0);
        List<Categorias> lista = controller.listarCategorias();
        for (Categorias c : lista) {
            model.addRow(new Object[]{c.getId(), c.getNombre()});
        }
    }

    private Categorias mostrarDialogo(Categorias c) {
        JTextField nombre = new JTextField();
        if (c != null) nombre.setText(c.getNombre());

        Object[] campos = {"Nombre:", nombre};
        int opcion = JOptionPane.showConfirmDialog(null, campos, "Categoría", JOptionPane.OK_CANCEL_OPTION);
        if (opcion == JOptionPane.OK_OPTION) {
            Categorias categoria = new Categorias();
            if (c != null) categoria.setId(c.getId());
            categoria.setNombre(nombre.getText());
            return categoria;
        }
        return null;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CategoriasFrame.class.getName());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CategoriasFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
