/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.EstadosController;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import modelo.Estados;
/**
 *
 * @author jaime
 */
public class EstadosFrame extends JFrame {
    private JTable table;
    private DefaultTableModel model;
    private EstadosController controller = new EstadosController();
    
    public EstadosFrame() {
        setTitle("Gestión de Estados");
        setSize(400, 300);
        setLayout(null);

        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"ID", "Nombre"});
        table = new JTable(model);
        JScrollPane scroll = new JScrollPane(table);
        scroll.setBounds(20, 20, 350, 150);
        add(scroll);

        JButton btnCrear = new JButton("Crear");
        btnCrear.setBounds(20, 180, 100, 30);
        add(btnCrear);

        JButton btnEditar = new JButton("Editar");
        btnEditar.setBounds(140, 180, 100, 30);
        add(btnEditar);

        JButton btnEliminar = new JButton("Eliminar");
        btnEliminar.setBounds(260, 180, 100, 30);
        add(btnEliminar);

        JButton btnRefrescar = new JButton("Refrescar");
        btnRefrescar.setBounds(140, 220, 100, 30);
        add(btnRefrescar);

        btnRefrescar.addActionListener(e -> cargarEstados());

        btnCrear.addActionListener(e -> {
            Estados estado = mostrarDialogo(null);
            if (estado != null) controller.crearEstado(estado);
            cargarEstados();
        });

        btnEditar.addActionListener(e -> {
            int fila = table.getSelectedRow();
            if (fila >= 0) {
                Estados es = new Estados();
                es.setId((int) model.getValueAt(fila, 0));
                es.setNombre((String) model.getValueAt(fila, 1));
                es = mostrarDialogo(es);
                if (es != null) controller.actualizarEstado(es);
                cargarEstados();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un estado");
            }
        });

        btnEliminar.addActionListener(e -> {
            int fila = table.getSelectedRow();
            if (fila >= 0) {
                int id = (int) model.getValueAt(fila, 0);
                controller.eliminarEstado(id);
                cargarEstados();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un estado");
            }
        });

        cargarEstados();
    }
    
    private void cargarEstados() {
        model.setRowCount(0);
        List<Estados> lista = controller.listarEstados();
        for (Estados e : lista) {
            model.addRow(new Object[]{e.getId(), e.getNombre()});
        }
    }
    
    private Estados mostrarDialogo(Estados e) {
        JTextField nombre = new JTextField();
        if (e != null) nombre.setText(e.getNombre());

        Object[] campos = {"Nombre:", nombre};
        int opcion = JOptionPane.showConfirmDialog(null, campos, "Estado", JOptionPane.OK_CANCEL_OPTION);
        if (opcion == JOptionPane.OK_OPTION) {
            Estados estado = new Estados();
            if (e != null) estado.setId(e.getId());
            estado.setNombre(nombre.getText());
            return estado;
        }
        return null;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EstadosFrame.class.getName());


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EstadosFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
