/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PrioridadesController;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import modelo.Prioridades;
/**
 *
 * @author jaime
 */
public class PrioridadesFrame extends JFrame {
    private JTable table;
    private DefaultTableModel model;
    private PrioridadesController controller = new PrioridadesController();

    public PrioridadesFrame() {
        setTitle("Gestión de Prioridades");
        setSize(400, 300);
        setLayout(null);

        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"ID", "Nombre"});
        table = new JTable(model);
        JScrollPane scroll = new JScrollPane(table);
        scroll.setBounds(20, 20, 350, 150);
        add(scroll);

        JButton btnCrear = new JButton("Crear");
        btnCrear.setBounds(20, 180, 100, 30);
        add(btnCrear);

        JButton btnEditar = new JButton("Editar");
        btnEditar.setBounds(140, 180, 100, 30);
        add(btnEditar);

        JButton btnEliminar = new JButton("Eliminar");
        btnEliminar.setBounds(260, 180, 100, 30);
        add(btnEliminar);

        JButton btnRefrescar = new JButton("Refrescar");
        btnRefrescar.setBounds(140, 220, 100, 30);
        add(btnRefrescar);

        btnRefrescar.addActionListener(e -> cargarPrioridades());

        btnCrear.addActionListener(e -> {
            Prioridades p = mostrarDialogo(null);
            if (p != null) controller.crearPrioridad(p);
            cargarPrioridades();
        });

        btnEditar.addActionListener(e -> {
            int fila = table.getSelectedRow();
            if (fila >= 0) {
                Prioridades p = new Prioridades();
                p.setId((int) model.getValueAt(fila, 0));
                p.setNombre((String) model.getValueAt(fila, 1));
                p = mostrarDialogo(p);
                if (p != null) controller.actualizarPrioridad(p);
                cargarPrioridades();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una prioridad");
            }
        });

        btnEliminar.addActionListener(e -> {
            int fila = table.getSelectedRow();
            if (fila >= 0) {
                int id = (int) model.getValueAt(fila, 0);
                controller.eliminarPrioridad(id);
                cargarPrioridades();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una prioridad");
            }
        });

        cargarPrioridades();
    }

    private void cargarPrioridades() {
        model.setRowCount(0);
        List<Prioridades> lista = controller.listarPrioridades();
        for (Prioridades p : lista) {
            model.addRow(new Object[]{p.getId(), p.getNombre()});
        }
    }

    private Prioridades mostrarDialogo(Prioridades p) {
        JTextField nombre = new JTextField();
        if (p != null) nombre.setText(p.getNombre());

        Object[] campos = {"Nombre:", nombre};
        int opcion = JOptionPane.showConfirmDialog(null, campos, "Prioridad", JOptionPane.OK_CANCEL_OPTION);
        if (opcion == JOptionPane.OK_OPTION) {
            Prioridades prioridad = new Prioridades();
            if (p != null) prioridad.setId(p.getId());
            prioridad.setNombre(nombre.getText());
            return prioridad;
        }
        return null;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrioridadesFrame.class.getName());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrioridadesFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
