/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.UsuariosController;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.util.List;
import modelo.Usuarios;
/**
 *
 * @author jaime
 */
public class UsuariosFrame extends javax.swing.JFrame {
    private JTable table;
    private DefaultTableModel model;
    private UsuariosController controller = new UsuariosController();

    public UsuariosFrame() {
        setTitle("Gestión de Usuarios");
        setSize(600, 400);
        setLayout(null);

        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"ID", "Nombre", "Email", "Rol"});
        table = new JTable(model);
        JScrollPane scroll = new JScrollPane(table);
        scroll.setBounds(20, 20, 550, 200);
        add(scroll);

        JButton btnCrear = new JButton("Crear");
        btnCrear.setBounds(20, 240, 100, 30);
        add(btnCrear);

        JButton btnEditar = new JButton("Editar");
        btnEditar.setBounds(140, 240, 100, 30);
        add(btnEditar);

        JButton btnEliminar = new JButton("Eliminar");
        btnEliminar.setBounds(260, 240, 100, 30);
        add(btnEliminar);

        JButton btnRefrescar = new JButton("Refrescar");
        btnRefrescar.setBounds(380, 240, 100, 30);
        add(btnRefrescar);

        btnRefrescar.addActionListener(e -> cargarUsuarios());

        btnCrear.addActionListener(e -> {
            Usuarios u = mostrarDialogo(null);
            if (u != null) controller.crearUsuario(u);
            cargarUsuarios();
        });

        btnEditar.addActionListener(e -> {
            int fila = table.getSelectedRow();
            if (fila >= 0) {
                Usuarios u = new Usuarios();
                u.setId((int) model.getValueAt(fila, 0));
                u.setNombre((String) model.getValueAt(fila, 1));
                u.setEmail((String) model.getValueAt(fila, 2));
                u.setRol((int) model.getValueAt(fila, 3));
                u = mostrarDialogo(u);
                if (u != null) controller.actualizarUsuario(u);
                cargarUsuarios();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un usuario");
            }
        });

        btnEliminar.addActionListener(e -> {
            int fila = table.getSelectedRow();
            if (fila >= 0) {
                int id = (int) model.getValueAt(fila, 0);
                controller.eliminarUsuario(id);
                cargarUsuarios();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un usuario");
            }
        });

        cargarUsuarios();
    }

    private void cargarUsuarios() {
        model.setRowCount(0);
        List<Usuarios> lista = controller.listarUsuarios();
        for (Usuarios u : lista) {
            model.addRow(new Object[]{u.getId(), u.getNombre(), u.getEmail(), u.getRol()});
        }
    }

    private Usuarios mostrarDialogo(Usuarios u) {
        JTextField nombre = new JTextField();
        JTextField email = new JTextField();
        JTextField rol = new JTextField();
        JPasswordField pass = new JPasswordField();

        if (u != null) {
            nombre.setText(u.getNombre());
            email.setText(u.getEmail());
            rol.setText(String.valueOf(u.getRol()));
        }

        Object[] campos = {
                "Nombre:", nombre,
                "Email:", email,
                "Password:", pass,
                "Rol:", rol
        };

        int opcion = JOptionPane.showConfirmDialog(null, campos, "Usuario", JOptionPane.OK_CANCEL_OPTION);
        if (opcion == JOptionPane.OK_OPTION) {
            Usuarios usuario = new Usuarios();
            if (u != null) usuario.setId(u.getId());
            usuario.setNombre(nombre.getText());
            usuario.setEmail(email.getText());
            usuario.setPassword(new String(pass.getPassword()));
            usuario.setRol(Integer.parseInt(rol.getText()));
            return usuario;
        }
        return null;
    }
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UsuariosFrame.class.getName());

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UsuariosFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
